name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: upload-artifact.yml
          name: artifact.sh
          path: webstore-build
          repo: Richard45364/webstore-frontend
          search_artifacts: true

      - name: Print content
        run: |
          bash ./webstore-build/artifact.sh
